# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/custom_code/**
    - lib/flutter_flow/custom_functions.dart
  
  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing returns as errors
    missing_return: error
    # Allow unused elements in generated code
    unused_element: info
    # Allow dead null aware expressions (common in null-safe migrations)
    dead_null_aware_expression: info
    # Allow unreachable switch defaults (can be intentional for exhaustiveness)
    unreachable_switch_default: info

linter:
  rules:
    # Additional rules beyond flutter_lints
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_this
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - sized_box_for_whitespace
    - use_key_in_widget_constructors
